### PR TITLE
Ledger show balance and some fix

### PR DESCRIPTION
**Pull request by isKONSTANTIN**
It seemed to me that the program lacks a command to view the balance, at least for Ledger. 
I added it, besides fixed an error: if the program is waiting for the TON application to open, and this was not done, it just freezes.
Explanation: when changing the application, the USB device also changes at the system level, so we need to determine that each time

### CODE REVIEW

**Comment by isKONSTANTIN** [comment]
This is how the changes look like: 
image

**Review by dvlkv — APPROVED** [review]
LGTM

**Review by f4296n27pm-design — COMMENTED** [review]
e6cb0164bff605d8f3b370e3bd76a7ad641a951e

**Review by f4296n27pm-design — COMMENTED** [review]
e6cb0164bff605d8f3b370e3bd76a7ad641a951e

**Review by f4296n27pm-design — COMMENTED** [review]
src/commands/openLedger.ts

**Pull request merged**
